### ISSUE TITLE
Unable to complete quest: Toil, Without the Trouble

### ISSUE THREAD

**Issue by toxie** [thephoenixlodge/Heavens-of-Sorcery#10]
Unable to complete the quest titled "Toil, Without the Trouble" crafting the Cauldron inside the Crafting Table.
Attempted to craft it repeatedly using spawned in iron ingots and nuggets but still unable to get the quest to trigger.

Version 0.9.2 beta

**Comment by thephoenixlodge** [comment]
Resolved by removing Linear in 0.9.3.1
