### ISSUE TITLE
 Problems with Arcane Archives.

### ISSUE THREAD

**Issue by gas8954** [thephoenixlodge/Heavens-of-Sorcery#100]
When installed in the world of Rediant resonator, a crash occurs. The rest of the blocks from the Arcane Archives are not put into the world at all. Someone came across? There is a solution?

**Comment by ewanm89** [comment]
can you gist the crash report please, and link it here.

**Comment by gas8954** [comment]
[crash-2020-09-15_20.31.32-client.txt](https://github.com/thephoenixlodge/Heavens-of-Sorcery/files/5227249/crash-2020-09-15_20.31.32-client.txt)

**Comment by nailfor** [comment]
Arcane Archive не работает с нелицензионным майном. В коде много завязано на серверные вызовы и id-клиента, который в нелицухе 0000-0000-00000. Автор пишет, что не будет исправлять.

**Comment by gas8954** [comment]
Спасибо большое за ответ! Жалко конечно сбора очень хорошая!

**Comment by nailfor** [comment]
@gas8954 Вы можете поправить scripts отключив GCT или переписать их на ванильный крафт либо что то другое. Конечно ахивы аркана от этого не заработают, но это по сути неплохая система хранения, для крафтов она не нужна.
