### ISSUE TITLE
Crash while loading client (log included)

### ISSUE THREAD

**Issue by LuciousLisa** [thephoenixlodge/Heavens-of-Sorcery#110]
I would love to play this pack, but I keep crashing when I try to run it.
Uploaded crash log here: [https://paste.ee/p/y3a3o](https://paste.ee/p/y3a3o)
I don't know how to read these logs. What can I do to allow myself to play?
Thanks for any help anyone could offer, much appreciated! <3

**Comment by ewanm89** [comment]
Is there a directory/folder called crash-reports with a log file in it, there are many inconsequential errors in the logs and the crash report will tell us which one it is and also some extra information about it specifically.

**Comment by LuciousLisa** [comment]
Thank you so much for your reply, Ewan!
I fear I may have spoken too soon. After dozens of crashes while attempting to launch the pack before I posted the issue, I find myself being able to do so without problems today. I can't tell you what changed, just that it works now. Magic perhaps?
Apologies for the unnecessary issue, I will close it and proceed to enjoy playing.
