### ISSUE TITLE
No snorkels for Rat Upgrade: Extra Breathe

### ISSUE THREAD

**Issue by ackeri** [thephoenixlodge/Heavens-of-Sorcery#111]
Artifact mimics don't drop snorkels, so there is no way to craft this upgrade or the upgrades requiring it. Related, I don't believe blue skies has a survival way to obtain a runic arc for the Battle-God upgrade.

**Comment by thephoenixlodge** [comment]
Fixed by https://github.com/thephoenixlodge/Heavens-of-Sorcery/commit/c61301e470ad0c4f28e683cca9d913649657afcf
