### ISSUE TITLE
Key Thaumcraft Items Unobtainable

### ISSUE THREAD

**Issue by RS-Mind** [thephoenixlodge/Heavens-of-Sorcery#112]
As far as I can tell, there is currently no way to obtain either amber or shimmerleaf. These items are necessary for certain Thaumcraft recipes/researches

**Comment by thephoenixlodge** [comment]
resolved by https://github.com/thephoenixlodge/Heavens-of-Sorcery/commit/ef0d016ba173b1699f9522dffa9b28b2f834b90c
