### ISSUE TITLE
[Blood Magic] Issue with Alchemy Table

### ISSUE THREAD

**Issue by HalestormXV** [thephoenixlodge/Heavens-of-Sorcery#114]
It would appear that there is a bit of a circulatory recipe issue. The Alchemy Table required Scorned Bricks and Scorned Bricks require  Spectral Dust. However spectral dust requires an Alchemy Table. Therefore making it currently impossible to get the Alchemy Table. This is on version 0.10.0 of the pack.

**Comment by RS-Mind** [comment]
Spectral dust is obtained by killing undead creatures with an arthana.

**Comment by OfficialRenny** [comment]
> 
> 
> Spectral dust is obtained by killing undead creatures with an arthana.

Athame*?
