### ISSUE TITLE
Food does not restore proper amount of saturation and hunger after 0.10.1-beta update

### ISSUE THREAD

**Issue by e-SonOfAnder** [thephoenixlodge/Heavens-of-Sorcery#120]
After updating the modpack to the current patch level, foods do not appear to be replenishing the correct amount of hunger and saturation.

Specific observation, eating steak with one haunch of hunger missing restores that single haunch of hunger and 1/2 a haunch of saturation. Have seen multiple reports of this issue in the general chat channel on the Discord with multiple types of food, though it seems like the everlasting foods may not be affected.

There are no visible debuffs showing that might be impacting this, and there is no Misty World affects on the character.

**Comment by thephoenixlodge** [comment]
resolved in 0.10.1.1
