### ISSUE TITLE
Dimensional Doors crashes new server when creating island

### ISSUE THREAD

**Issue by MrTubzy456** [thephoenixlodge/Heavens-of-Sorcery#122]
Brand new server and Dimensional Doors is crashing the server when players try to join and create an island. Here's a link to the crash report: https://pastebin.com/kF7DMVCp

**Comment by thephoenixlodge** [comment]
try a fresh world. It seems a dimdoors gateway is trying to spawn on the island, and having issues with the water there

**Comment by MrTubzy456** [comment]
ok will do, thanks for the fast reply
