### ISSUE TITLE
Nature's Aura's "Book of Natural Aura" is not progressing past the chapter "Brilliant Trees"

### ISSUE THREAD

**Issue by farigiss** [thephoenixlodge/Heavens-of-Sorcery#127]
The chapter "Brilliant Trees" in the Book of Natural Aura requires crafting gold powder to progress and unlock more chapters.
Because gold powder's crafting recipe is changed to require an Astral Sorcery grindstone, it gets stuck there.
It's pretty difficult to use Nature's Aura without the book's guidance.

**Comment by thephoenixlodge** [comment]
Use the version of the nature's aura book that says its added by patchouli. AKA the one that's actually craftable, given as a quest reward and has updated advancement pointers. Your issue is only encounterable if you cheat in the untweaked version.
