### ISSUE TITLE
Add a server file

### ISSUE THREAD

**Issue by AndersSpear** [thephoenixlodge/Heavens-of-Sorcery#13]
Would it be possible to add a server .zip file with each update that includes the forge and Minecraft servers + a .BAT file to run it?

**Comment by AndersSpear** [comment]
The server kept crashing until I removed FancySpawnEggs aswell

**Comment by thephoenixlodge** [comment]
Server files are in the works. We've just been focused on getting a stable version out for singleplayer first

**Comment by AndersSpear** [comment]
thank you
