### ISSUE TITLE
Questbook on server not syncing with advancements

### ISSUE THREAD

**Issue by crafter312** [thephoenixlodge/Heavens-of-Sorcery#143]
I recently set up a Heavens of Sorcery server on my computer to try it out with some of my friends. However, I've been having a weird problem with the quest book. When I was checking through the existing issues, I learned that the quest book system is based on advancements. I am able to play through and complete the advancements normally, and it gives me rewards and everything. However, the quest book has not been showing any of the quests as being completed. 

Saving the World 101 is stuck with the first two quests showing as incomplete: "! Preface - Read Me First" and "An End and a Beginning." I've got my island set up properly, crafted a wooden wand, and have completed the first few advancements up through making diamonds, and the quests are still stuck like that.

Here is the YouTube video I followed to remind myself how to set up a modpack server, just in case there is an issue arising from that: https://youtu.be/7qqbd1RovSU

**Comment by ewanm89** [comment]
1) Server files are available [here](https://www.curseforge.com/minecraft/modpacks/heavens-of-sorcery/files/3086231) (they work with current client which is 0.10.1.3-beta.

**Comment by crafter312** [comment]
Thank you so much! I did not know they worked with the current client.
