### ISSUE TITLE
Salis Mundus will not turn transform bookshelf

### ISSUE THREAD

**Issue by Sutysuty** [thephoenixlodge/Heavens-of-Sorcery#153]
As said in the title, salis mundus does not create the thauminomicon when I right click on a bookshelf. Is this a bug or is the progression locked once you reach the between lands due to it being a beta version?

**Comment by GrowlingGiant** [comment]
You need to use the salis mundus on a menhir in the betweenlands to make a thaumonomicon. Shortly afterwards you will need to substitute a weedwood crafting table instead of a regular crafting table to make the Thaumcraft crafting table.

**Comment by Sutysuty** [comment]
Thanks.
