### ISSUE TITLE
Generator Settings?

### ISSUE THREAD

**Issue by XiNaru** [thephoenixlodge/Heavens-of-Sorcery#159]
What are the generator settings to create the right world on a server?

**Comment by ewanm89** [comment]
It should all be set up if you use the server files from curseforge.

**Comment by XiNaru** [comment]
there are no GOOD server files ....

there is only an override folder in the zip that cannot be used by a server as a rule.

sry but as it is there I can't build a server. no explanation whatsoever.

**Comment by mov51** [comment]
Do you mean an explanation like this? 
![image](https://user-images.githubusercontent.com/16448318/119012272-e2a07700-b963-11eb-9949-85851e9318f2.png)

**Comment by ewanm89** [comment]
The one I put in there deliberately!

**Comment by XiNaru** [comment]
it works, i hadn't seen that.


but another question .. is there a way to remove such a rift? I summoned it because of a mistake and yes ...

**Comment by mov51** [comment]
No, there is no way to remove rifts.
