### ISSUE TITLE
Reliable way to get Apples

### ISSUE THREAD

**Issue by Jomeaga** [thephoenixlodge/Heavens-of-Sorcery#16]
Could we get a more reliable way to get apples? I wanted to brew Rustic's ale but the apple oak is incredibly slow at producing apples and you cannot bone meal the fruit.

Perhaps make Rustic's Apple sapling craftable?

EDIT: on that note, the other Rustic crops would be nice to have as well.

**Comment by thephoenixlodge** [comment]
I vaguely recall making most of the Rustic plants available through various types of dungeon loot, and maybe in the drops from grass in the everbright/everdawn. I might look at making the Rustic apple tree an upgrade from the other one, by botania mana infusion or some other way.

**Comment by Jomeaga** [comment]
Oh yes, I've just gotten to the first dungeon raid and been finding some of the other rustic plants.

That sounds like a good way to get the Rustic apple tree, if it's not too late in the pack.

**Comment by Jomeaga** [comment]
Seems like you have everything covered for Rustic except for the Apple tree and the Bees (which are really useful for nice candles, crop acceleration, and brewing)

**Comment by Jomeaga** [comment]
Okay I found Rustic Beehives, but they only occur on Misty world's Jungle biome. Is that intended? Couldn't find it in swamps, plains, or snow.
