### ISSUE TITLE
Throwing RedStone Block/Dust in fire doesn't create Devils Dust

### ISSUE THREAD

**Issue by abelwatson** [thephoenixlodge/Heavens-of-Sorcery#161]
I tried both the block and the just the dust, but the dust just burns up, and the block just continues to sit there. I even did it in an area where nothing else can catch fire

**Comment by ZephyrWindSpirit** [comment]
Is fire tick turned on or off.

**Comment by abelwatson** [comment]
What do you mean by fire tick?

**Comment by abelwatson** [comment]
Issue solved with using a longer lasting fire.
