### ISSUE TITLE
Crash on start :(

### ISSUE THREAD

**Issue by GameHost01** [thephoenixlodge/Heavens-of-Sorcery#162]
The game doesnt start
Here is the log from the logs folder
[https://paste.feed-the-beast.com/view/4652dad4](url)

**Comment by ewanm89** [comment]
You solved it I assume?
It looks like something wrong with the minecraft install, would recommend reinstalling the pack.

**Comment by GameHost01** [comment]
> 
> 
> You solved it I assume?
> It looks like something wrong with the minecraft install, would recommend reinstalling the pack.

Thats exactly what i did :)
