### ISSUE TITLE
Bugged Corail/Botania/Aether Enchantment Interaction

### ISSUE THREAD

**Issue by LordRaine** [thephoenixlodge/Heavens-of-Sorcery#164]
While attempting to create multiple Books of Disenchantment for the purposes of enchanting, I discovered that the custom recipe for creating them in the Hellfire Forge will only accept a Spellbinding Cloth at full durability [Bug 1]. I then attempted to restore the Cloth's durability by placing it in an Altar from the Aether. This caused a runaway reaction where every time a shard of Ambrosium was consumed to "heal" the item, it instead took one durability from the Spellbinding Cloth and created a full-durability duplicate Cloth in the output [Bug 2]. The end result being a nearly-depleted Spellbinding Cloth and over twenty full-durability duplicates. 

-The Hellfire Forge recipe for Books of Disenchantment needs to be changed to recognize Spellweave Cloth with less-than-full durability.

-The Aether Altar's interaction with Spellbinding Cloth either needs to be changed, or the Cloth should be blacklisted from working with the Altar at all.

**Comment by thephoenixlodge** [comment]
Resolved by https://github.com/thephoenixlodge/Heavens-of-Sorcery/commit/591c676a88005f285f5530ecccf4e764eeaf47c3
