### ISSUE TITLE
Crash On World Load (Gaia Guardian/Misty World?)

### ISSUE THREAD

**Issue by LordRaine** [thephoenixlodge/Heavens-of-Sorcery#165]
While fighting the Gaia Guardian in an arena I had built in the Misty World, I experienced a hard crash that threw me all the way back to my launcher (ATLauncher).  When attempting to reload the world, it appeared to fully load everything but crashed before putting me into the game. After repeating this several times, I backed up my save and did a clean reinstall of the pack. Even after reinstalling, the same error occurred. My single player world (on the Enter The Betweenlands step) is currently unplayable. 

https://pastebin.com/akp5xPPG

**Comment by LordRaine** [comment]
Pretty disappointed overall in this error. I loved the pack and was enjoying playing it, but it never feels good to watch an elaborate base you've spent 100+ hours building and decorating go up in smoke. I'm not sure if this pack is even still being developed, but hopefully whatever caused this gets fixed and my world isn't permanently corrupted.

**Comment by ewanm89** [comment]
Well, it looks like the issue is on your player itself, specifically thaumcraft adding warp conflicting with natural pledge due to baubles....
Can you send your player.dat file please? Maybe via Discord, you'll find me on TPL's discord server.

**Comment by LordRaine** [comment]
> Well, it looks like the issue is on your player itself, specifically thaumcraft adding warp conflicting with natural pledge due to baubles....
> Can you send your player.dat file please? Maybe via Discord, you'll find me on TPL's discord server.

I uninstalled Discord some time ago, but if you need those files, I can reinstall it to send them to you. Is TPL's discord the one linked on the CurseForge page?

Also, if it's a conflict between Thaumcraft Warp and Natural Pledge, I have a guess as to what may have happened. The Sunmaker Armor from NP has a set bonus that spends inventory mana from Botania to prevent all negative status effects from being applied to the player. It's a pretty strong blanket effect: not only does it make you totally immune to things like wither, but it also means debuffs like Soul Fray from Blood Magic never get applied to you either. That's really strong for doing things like using a sacrificial dagger to self-sacrifice life points into a blood well. 

I was wearing the Sunmaker Set as well as the Traveler's Ration Belt during that fight, both from NP. You know what the sun set does; the ration belt feeds food in your inventory to the player automatically when they take hunger damage. So what probably caused the crash is my character picking up a zombie brain from the Guardian's spawned mobs (which is edible and applies warp), and then the ration belt attempting to feed it to me. Either the interaction between zombie brains and the belt is bugged, or it's not, but the interaction of getting warp applied to you while wearing the Sunmaker Set is bugged.

**Comment by ewanm89** [comment]
Right, I was thinking something along those lines. I can tell you it is having issues with casting item type in natural pledge item in baubles when adding warp from eating zombie brain... I'm going to guess the traveler's ration belt. Though other times warp is an issue my be a problem too.  I would edit nbt to remove the zombie brain from inventory, that should allow one to load the world again.

**Comment by LordRaine** [comment]
I am going to close this issue, because I made a very foolish mistake. Before I deleted HoS and attempted a clean install, I had manually copied and saved my data to the desktop, so I could simply drag and drop it back and get my world returned. I did this, and naturally it crashed again, because as we've already established, the crash was likely being caused by an ongoing reaction in the game between NP accessories and Thaumcraft warp. However, what I didn't consider is that by dragging and dropping it to replace it, I lost the manual copy on my desktop, so when I deleted everything to attempt a clean world gen, I actually lost all of my saved data without realizing it, believing I still had the backup on my desktop. A rookie mistake. 

I have also now had the pleasure of discovering that while Windows 10 does indeed have a clipboard memory feature, meaning you can go back and find things you had previously copied and pasted to the clipboard, it doesn't come activated by default. Because why on earth would a useful feature you'll need to recover from an accident already be running? 

So unfortunately, I can no longer return to that world in any case, nor can I provide the player.dat file for the purposes of chasing down the bug. So this topic no longer needs to remain open. I sincerely apologize. I don't know if the crash was caused by the Sun armor trying to stop warp being applied, the belt making me eat a brain, or some combination of the two, but I can back up my new current world and test it when I reach that point. I will be happy to provide the logs I generate from doing this when I reach that point.

Thank you for responding to my issue, ewanm89, and I appreciate your time.

My advice to anyone reading this is to avoid accessories or items that cause you to automatically interact with other items that might be modded and carry modded effects, like the Traveler's Ration Belt.

**Comment by ewanm89** [comment]
Well, generally we do want to know about such conflicts. We can then try to blacklist the interactions and such. In this case I can't see a way to do it without modifying the mods themselves though.
