### ISSUE TITLE
bug where you cant get leather from cows

### ISSUE THREAD

**Issue by ZappierFour50** [thephoenixlodge/Heavens-of-Sorcery#167]
title sums it up but there's no way to get leather from cows
edit-sorry I meant the summoned cows+and the jei says nothing for cows

**Comment by ewanm89** [comment]
cutting.zs:
```zenscript
addCuttingMeat("cow", "minecraft:entities/cow", {"pool1" : {<minecraft:beef> : [1, 2]}, "main" : {<minecraft:leather> : [1, 2]}});
```

Yes leather does drop from cows, JEI does not understand our dynamic modifying of the drop tables to link to cutting skill though.
