### ISSUE TITLE
DimDoors dungeon portal on spawn island.

### ISSUE THREAD

**Issue by Roxforbraynz** [thephoenixlodge/Heavens-of-Sorcery#169]
Some seeds can spawn the DimDoors dungeon portals on the spawn island. It should be possible to blacklist the overworld in the config or drop the generation chance to zero if this behavior isn't intended.

One such seed is -472742362868097766

![2022-01-27_03 28 43](https://user-images.githubusercontent.com/10597104/151342688-92875008-45b3-4ebe-9e58-19f291bac95b.png)

**Comment by thephoenixlodge** [comment]
We've tried to fix this before. The config option in DimDoors is bugged and disabling them from spawning in any dimension disables them completely. It's a fairly rare occurrence anyway.
