### ISSUE TITLE
Terracotta shingles recipe conflict

### ISSUE THREAD

**Issue by chadandersen1** [thephoenixlodge/Heavens-of-Sorcery#17]
The normal Terracotta shingles from Quark are uncraftable, colored ones can be crafted.

**Comment by thephoenixlodge** [comment]
They are craftable, just using Cathedral's fired clay tiles, to add consistency between similar block types. Looks like there's a few recipe conflicts around there though. I'll have to take a look at tidying that up more

**Comment by chadandersen1** [comment]
Yes there is a recipe for them but the same recipe applies to Cathedral Shingles or whatever they are which don't look as good IMO, making Quark ones completely uncraftable unless a mod like NoMoreRecipeConflict is installed. I would prefer if they were crafted using Cathedral's clay tiles like you say but that is not the case.

**Comment by chadandersen1** [comment]
That being said I didn't first check if there was a way to dye them/wash them back to terracotta color so my bad if there truly is a way to get them

**Comment by thephoenixlodge** [comment]
yea the recipes for those coloured shingles is exactly what I meant by "looks like there's a few recipe conflicts around there though" . They don't make sense at all and I have no idea where they came from - they didn't exist when I changed this stuff initially
