### ISSUE TITLE
Server zip file should not include the libraries folder, forge executable, or Minecraft

### ISSUE THREAD

**Issue by ArbitraryHubris** [thephoenixlodge/Heavens-of-Sorcery#20]
Including the correct forge installer and a script to kick that off will get the server set up by downloading the correct libraries for the server's operating system, as well as the Minecraft jar file.

**Comment by mov51** [comment]
This will be fixed with the next server release. It was a mistake on my part that Ewanm89 is fixing. The updated server pack for 9.4 should be released tomorrow.

**Comment by thephoenixlodge** [comment]
This is sorted, so I'll close the issue. Only reason server files aren't already there is cos Curseforge is having trouble actually processing them for some reason
