### ISSUE TITLE
Quest book order issue

### ISSUE THREAD

**Issue by AranaiRa** [thephoenixlodge/Heavens-of-Sorcery#22]
This isn't a functionality issue, but is very confusing to approach as a player. The quest that explains how to get leather (by summoning a cow) comes after the quest to make the Arcane World ritual table, which requires a book. As there's no way to get string before this point (that I could tell, anyway), it leads to a frustrating roadblock for the player.

**Comment by ewanm89** [comment]
There is a limitation in the way the quests are done that we can't have multiple prior quests as dependencies, so from time to one quest line can be taken a bit ahead of another and one has to do the other branch a bit to get resources you need.

**Comment by thephoenixlodge** [comment]
And the ritual table specifically doesn't require a book, just a piece of paper, cos it's what you use to get cows in the first place...
