### ISSUE TITLE
its not i big issue, but i cant get string! i dont see spiders, no string or leather on nether chests, so i cant make a book

### ISSUE THREAD

**Issue by umotakuretardado** [thephoenixlodge/Heavens-of-Sorcery#24]

**Comment by umotakuretardado** [comment]
if you know how to get leather is good too

**Comment by chadandersen1** [comment]
summon cow

**Comment by Ariselir** [comment]
For Leather, just Summon cows, have to kill pigmen to get flesh for the beef, string i've gotten from The Misty World, but not sure about earlier on...
