### ISSUE TITLE
okay, now i got a problem, i was searching ice, and when i have written ic, minecraft crashed, and i cant open inventory

### ISSUE THREAD

**Issue by umotakuretardado** [thephoenixlodge/Heavens-of-Sorcery#25]
[crash-2020-07-25_14.33.53-client.txt](https://github.com/thephoenixlodge/Heavens-of-Sorcery/files/4976109/crash-2020-07-25_14.33.53-client.txt)

if you wanna a video i have it, just donr know how to upload it

**Comment by ewanm89** [comment]
As optifine is not included in the pack and this is the start of the stack trace, we can not support this:
```
java.lang.NullPointerException: Rendering Block Entity
	at net.optifine.EmissiveTextures.getEmissiveTexture(EmissiveTextures.java:96)
```

**Comment by Saphrym** [comment]
That looks like you have Optifine installed so something with "ic" is trying to render and Optifine is crashing it.. Have you tried it without Optifine?
