### ISSUE TITLE
Aether mob spawning?

### ISSUE THREAD

**Issue by Ariselir** [thephoenixlodge/Heavens-of-Sorcery#26]
I am currently at "Don't Lick the Lead" in the Quest book and i believe there is a progression block. It seems that Aether mobs aren't spawning (except for bosses and valkyries) and as such, Aechor Plants don't spawn, which are needed to make lead. May have to reenable that unless there's another way to get Aechor Petals.

**Comment by thephoenixlodge** [comment]
known bug already fixed for next update

**Comment by Ariselir** [comment]
coolio
