### ISSUE TITLE
Duplicate Apple Pip recipe

### ISSUE THREAD

**Issue by Jomeaga** [thephoenixlodge/Heavens-of-Sorcery#29]
Dynamic Tree's Apple Pip already had a recipe in the form of Ironberry seeds + Wildberry juice in a cauldron. New mana infusion recipe seems pointless?

Should this be a recipe for the Rustic Apple Tree sapling instead?

**Comment by thephoenixlodge** [comment]
That's exactly what it is. The rustic version of the dynamic apple tree tends to produce more apples.
