### ISSUE TITLE
0.9.4 Chili Powder->Redstone broken

### ISSUE THREAD

**Issue by SuohKami** [thephoenixlodge/Heavens-of-Sorcery#31]
Throwing Chili Powder into fire to make Redstone seems to be broken in this version.

**Comment by ewanm89** [comment]
Works fine for me. There is a particle effect when it happens.

**Comment by SuohKami** [comment]
Yea, it started working now. I don't know why it wasn't. Is there a requirement set for a quest to be completed before it works? I got all the way to making the nether portal before it started working.
