### ISSUE TITLE
Manasteel Pick has no drops when mining Misty World Coal

### ISSUE THREAD

**Issue by Jomeaga** [thephoenixlodge/Heavens-of-Sorcery#36]
Manasteel picks mine Misty World's coal ore at a good speed, but then there are no drops. I tried on several pieces of ore.

I was getting drops from other ores.

**Comment by MaxAstro** [comment]
On the one hand, it's probably intentional that only nionite picks drop the coal, for progression reasons.

On the other hand, since you literally need nionite to make manasteel, I totally see your point.  :)

**Comment by ewanm89** [comment]
@MaxAstro niobium being needed to make manasteel is precisely why we made it so manasteel can mine mistyworld stone. Botania picks are after niobium in the progression of the pack.
