### ISSUE TITLE
Sound Muffler

### ISSUE THREAD

**Issue by Jomeaga** [thephoenixlodge/Heavens-of-Sorcery#37]
Request to add a sound muffler mod of some kind. Dispensers and automation pieces are REALLY loud.

**Comment by DynamOdin** [comment]
Botania has the Bergamute flower for that

**Comment by thephoenixlodge** [comment]
Super Sound Muffler Revived being added in 0.9.5. The original version of it had been in the pack previously, but then get hit by a drama stick so had to be removed
