### ISSUE TITLE
Shield of Repulsion Repulses Mana Spreader Projectiles

### ISSUE THREAD

**Issue by Ariselir** [thephoenixlodge/Heavens-of-Sorcery#42]
Basically the The Aether's Shield of Repulsion repulses / redirects a Mana Spreaders projectile. Not sure about the consequences, it does delay the spreader but i am unsure on if it wastes that shot of mana

I'd upload a gif but the program i used records them way too large. (way over the 10mb limit here)

**Comment by ravenascendant** [comment]
It is actually pretty cool looking although it did almost cause issues with my bore lenses breaking things they shouldn't, definitely wasted alot of Mana.

However because the Mana blaster can be used for pvp this is probably intended behavior.

**Comment by thephoenixlodge** [comment]
not really a bug. Mana pulses are projectiles, and the shield is just deflecting them like all projectiles.
