### ISSUE TITLE
Architecturecraft Architect's Sawbench is slightly harder to acquire than intended

### ISSUE THREAD

**Issue by Genderi** [thephoenixlodge/Heavens-of-Sorcery#45]
Version 0.9.4-beta

Despite being unlocked in the questbook upon acquisition of iron, the Architect's Sawbench cannot be crafted immediately because of the wooden pressure plate in its recipe. Ironwood currently cannot be turned into a wooden pressure plate, so access is artificially barred until other wood types are available.

**Comment by thephoenixlodge** [comment]
already resolved for next update
