### ISSUE TITLE
Where to Find Ventium?

### ISSUE THREAD

**Issue by MaxAstro** [thephoenixlodge/Heavens-of-Sorcery#48]
I can see that it's a Blue Skies ore, but Blue Skies has terrible documentation.  A lot of other ores (i.e. horizonite) have tooltips hinting where to find them, but ventium has nothing.  I've caved around in both the Everbright and Everdawn for quite a while and haven't come up with anything.

**Comment by thephoenixlodge** [comment]
Frostbitten Forest biome
