### ISSUE TITLE
[Item Duplication] Ring of Magnetism II + Hopper = Placeable Items Duping

### ISSUE THREAD

**Issue by wormwoodworms** [thephoenixlodge/Heavens-of-Sorcery#49]
Having Ring of Magnetisation II (from Extra Alchemy) equipped, while mining any placeable item that sits on a hopper, gives you that item in your inventory, while also sending one down the hopper line. I've duplicated quite a few Drying Basins by accident.

Seems to work with anything you can place on a hopper - confirmed with cauldron, log, soul sand, Ritual Table and block of Amethyst, as well as Beacon I cheated in for testing.

**Comment by thephoenixlodge** [comment]
Does this happen with the Magnetism potion effect in general? Or is it specific to when using the ring?
