### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SummitSummit** [thephoenixlodge/Heavens-of-Sorcery#52]
Suggestion:  Craft Otherworlds' Core with Reforging Token to get 2 Reforging Tokens.
I'm still early in the pack so I might be missing something, but it seems like there is NO use for more than 4 Cores, but I got 6 of them on my first dungeon raid.  I've done more than 10 raids but only gotten 6 total Reforging Tokens.  All gone and wish I had loads more.

**Comment by thephoenixlodge** [comment]
There's currently 5 uses for the otherworlds core - 2 for misty world portal, 1 for aether portal, 1 for underworld portal, and 1 for upgrading a builders bag.
I have buffed the drop rates of the reforging token in dev now, and added a couple of recipes for making them from otherworlds cores
