### ISSUE TITLE
Unable to download the modpack "Unable to get Addon: Together Forever (285968) - File ID: 2700901"

### ISSUE THREAD

**Issue by manianime** [thephoenixlodge/Heavens-of-Sorcery#53]
On Twitch, I cant download the modpack..

This is the message : This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 231951

Any idea ?

Thanks

**Comment by ewanm89** [comment]
It is very strange as 231951 is Immersive engineering which is not in the modpack. The issue itself seems to be something in the twitch client as it seems fine downloading and installing via multimc.

**Comment by thephoenixlodge** [comment]
Yea seems twitch is having issues in general presently - as an alternative, I suggest using the GD launcher, or manually downloading the zip directly from CF to install through MultiMC

**Comment by Dr4g0nBlade** [comment]
I tried to install it with GDLauncher and it failed to download multiple "addons" while most of them, are successful after trying, but the addon id: `226406` constantly fails

**Comment by thephoenixlodge** [comment]
well damn, guess GDLauncher is affected by the same issues Twitch is having then. You'll have to use MultiMC for now then

**Comment by Toksyuryel** [comment]
That would make it an API-level issue with either Twitch or Curseforge. Just tested with MultiMC, which does not use the API at all, and it works perfectly.

**Comment by ewanm89** [comment]
multimc does use the API, it has to as the zip doesn't include the different files but a manifest telling them to download. It is possible however it is the initial getting said zip file that is the problem in GD Launcher and Twitch, which means one could in theory download the zip file manually and import it into said clients. I don't know about GD Launcher, but there is a manual import from zip in Twitch.

**Comment by Dr4g0nBlade** [comment]
I can confirm that MultiMC worked, while Twitch and GDLauncher didn't. (Even with importing the ZIP)

**Comment by manianime** [comment]
I just make it work with MultiMC. What about the Update, do we have to download the news zip every time ?

**Comment by ewanm89** [comment]
Yeah, download zip, install to new instance and copy across the following files and directories:
```
BotaniaVars.dat
astralsorcery
betweenlands_gallery
journeymap
options.txt
patchouli_data.json
saves
servers.dat
```

**Comment by Riernar** [comment]
MultiMC [doesn't use the actual TwitchAPI](https://github.com/MultiMC/MultiMC5/blob/develop/api/logic/modplatform/flame/FileResolvingTask.cpp#L5), but a [different one](https://cursemeta.dries007.net/). I think that's why it doesn't fail.

I also tried with my custom tool, and I can confirm that Custom Main Menu (id `226406`) systematically fails as of now, the twitch API returns an http 404 error.

**Comment by ewanm89** [comment]
It is still using the API, just not directly. It certainly may be immunising against the issues by caching the data.

**Comment by thephoenixlodge** [comment]
Twitch's issues seem to be resolved, so this can be closed now
