### ISSUE TITLE
missing jei

### ISSUE THREAD

**Issue by reji8627** [thephoenixlodge/Heavens-of-Sorcery#54]
version .9.5 apparently doesn't have jei in it.

**Comment by Toksyuryel** [comment]
JEI is definitely there. You may have pressed ctrl+O to hide it

**Comment by reji8627** [comment]
no, I mean when i open the pack it doesn't load beacuse jei isn't in there, since it is a requirement for other mods.
[latest.log](https://github.com/thephoenixlodge/Heavens-of-Sorcery/files/5079432/latest.log)

**Comment by ewanm89** [comment]
Curseforge had some recent issues, so pack download problem is possible. Maybe close this if you have solved it?

**Comment by thephoenixlodge** [comment]
Twitch's issues seem to be resolved, so this can be closed now
