### ISSUE TITLE
Aechor Petal Buff

### ISSUE THREAD

**Issue by haighyorkie** [thephoenixlodge/Heavens-of-Sorcery#57]
Not an issue but a consideration. I find making lead to be heavily dependant on the ease of finding Aechor petals which in my experience has been incredibly difficult and time-consuming. To balance this I would consider buffing the drops from 1 to 2 petals per kill. This way looting on a sword is not essential but advantageous in gaining more whereas the person with no looting still has to kill quite a few to get what they need

**Comment by thephoenixlodge** [comment]
Covered by their inclusion in the cutting system as of 0.9.6
