### ISSUE TITLE
Misty World Portal generating in a very high place, above the top of the mist.

### ISSUE THREAD

**Issue by creiwen** [thephoenixlodge/Heavens-of-Sorcery#59]
Okay so I did some poking around my Misty World in Creative Mode (thanks to folks who gave me that idea).  I've attached a pic with coordinates and stuff, the portal generated in at Y 128, which is pretty high up, no?  The mist doesn't reveal any land, either, not even at night, in ANY direction.  In creative, I went down below the mist.  there's land, allllll the way down, and none of the fog recedes at night.  If I can't touch the mist without dying, I don't see how I'm supposed to get the things which are in this world to make for the equipment that protects me from the mist.

I can't even figure out how to use soap which I cheated-in, to reset my contamination level. It doesn't want to work when I stand in water and rightclick :( This is frustrating.  Am I using it right? That's the only logical way I can figure to use an item.

I also tried closing down, deleting the DIM5 folder, and changing the mist config file, to give me a new seed, and none of that worked, probably did it about five or six times before I just called it quits. It's the same exact seed every time and I know this because I recognize the shape of the land on the minimap. Please help!

**Comment by creiwen** [comment]
![2020-08-19_00 03 22](https://user-images.githubusercontent.com/60205120/90591029-06a21280-e1b0-11ea-9a4c-6b710a6041e1.png)

**Comment by haighyorkie** [comment]
filter coal generates further up. Go along the cliffs biome to mine some, then you can make the equipment you need to go into the mist fully

**Comment by creiwen** [comment]
There is no land, ANYWHERE, above the fog. That is the problem.

**Comment by lemonbarking** [comment]
That seems like just a really bad spawn. The y coordinate is correct. You spawn at higher elevations in the misty world. There are massive "seas" of fog so maybe your portal came out in the middle of one? For science try flying out a bit, the land there spawns as "islands" of biome types so I could totally see your situation happening.

**Comment by ravenascendant** [comment]
https://docs.google.com/document/d/17RVXOlnm5acTDLpJ9rf8pnLdXRQVUNiJJvr9MXkzcAQ/edit?usp=sharing

that is the collected wisdom of the discord channel on how to fix this issue. Unfortunately the technical fix described on the mod's curse page is currently not implemented in the mod, so this is all we have.

**Comment by thephoenixlodge** [comment]
A workaround for this was included in 0.9.6 with the Rift summon recipe. Unfortunately not much else can be done
