### ISSUE TITLE
Graves don't store Aether baubles and will fly potentially far away on death

### ISSUE THREAD

**Issue by VallenFrostweaver** [thephoenixlodge/Heavens-of-Sorcery#60]
Minecraft 1.12.2
Forge 14.23.5.2854
HoS version 0.9.5 beta
TombManyGraves version 4.2.0
Aether Legacy version 1.4.4

Upon death (I died from fall damage) my Aether items that are stored on the Aether inventory (tiny cloud icon in player inventory menu) drop or are deleted. I was wearing an Invisibility cloak and diamond gloves. The gloves were on the ground next to my grave and the cloak was a dozen blocks away. This may be needed to be reported to TombManyGraves instead of here but I thought it was worth a mention as these Aether "baubles" are rare rewards and often not craftable and this could lead to some rare item loss.

**Comment by ewanm89** [comment]
Actually, this is an Aether Legacy issue: https://github.com/M4thG33k/TombManyGraves2/blob/f98cfdbec9aa38674e9489b82ae3ad135d0b0b77/src/main/java/com/m4thg33k/tombmanygraves/inventory/AetherLegacyInventory.java#L14

Given they have moved to a new team maintaining that mod, I'll speak to them about this.

**Comment by thephoenixlodge** [comment]
Won't be an issue with the upcoming switch back to Corail Tombstone
