### ISSUE TITLE
More of a question

### ISSUE THREAD

**Issue by Vexsanity** [thephoenixlodge/Heavens-of-Sorcery#64]
I can't figure out what mod is adding step assist. I have auto jump set to off but I am still getting step assist from something. Thanks for your help.

**Comment by Toksyuryel** [comment]
Quark gives you step-assist if you have Jump Boost II.

**Comment by Vexsanity** [comment]
I don't have jump boost II currently

**Comment by Toksyuryel** [comment]
Then it must be some piece of equipment you're using. Come to the discord so we can discuss this properly, this tracker isn't the place for this.

**Comment by Vexsanity** [comment]
I would have done that if I could have found a discord link

**Comment by Vexsanity** [comment]
I ended up figuring it out anyways, it was the random stats that items get, my boots have step height 0.5.

**Comment by Toksyuryel** [comment]
> I would have done that if I could have found a discord link

The discord link is on the pack title screen.
