### ISSUE TITLE
Cows have no drops

### ISSUE THREAD

**Issue by jakethesnake1126** [thephoenixlodge/Heavens-of-Sorcery#65]
As title says, currently in 9.6 and 9.6.1, cows have no drops.

**Comment by thephoenixlodge** [comment]
in 0.9.6 I would expect this, as it is related to the bug that was hotfixed by 0.9.6.1. However, I just tested and it is working fine in 0.9.6.1 for me.

**Comment by Genderi** [comment]
Cows have regular drops, they're just missing from the JER mob drops section of JEI, which was probably the cause of confusion.

**Comment by thephoenixlodge** [comment]
Ah. Yea, unfortunately JER isn't very smart, nor configurable with its mob drops display

**Comment by McFrugal** [comment]
They definitely have less drops than normal.  They're supposed to drop at least 1 beef, and that is not the case.

**Comment by ewanm89** [comment]
That is actually be by design. They have been tied into the cutting skill of misty world, number of drops depends on skill level. Cutting level one is a 50% chance to get one (without looting).
