### ISSUE TITLE
World freezes on opening, after a crash

### ISSUE THREAD

**Issue by EtenKillbeat** [thephoenixlodge/Heavens-of-Sorcery#68]
While going betweeen the nether and the overworld, the game crashed for an unknown reason. Afterwards, the world freezes immediately after opening it . Not sure which log I should add, so I'll add the two closest to the moment of the crash.
[2020-08-25-1.log.gz](https://github.com/thephoenixlodge/Heavens-of-Sorcery/files/5122271/2020-08-25-1.log.gz)
[2020-08-24-1.log.gz](https://github.com/thephoenixlodge/Heavens-of-Sorcery/files/5122274/2020-08-24-1.log.gz)

**Comment by ewanm89** [comment]
You are getting an error about a zombie pigmen getting hurt. Suggest you go into `config/forge.cfg`, set `B:removeErroringEntities` to `true` then starting the pack and loading in and going to the nether. Then close and set the config option back to `false`

**Comment by LilyFlower5683** [comment]
Hi, I am also having this exact problem and I am unsure of where to find config/forge.cfg to try the fix that was suggested.
