### ISSUE TITLE
Spellforger's Codex flip page hotkey does not work

### ISSUE THREAD

**Issue by e-SonOfAnder** [thephoenixlodge/Heavens-of-Sorcery#69]
At the top of the Spellforger's Codex when held in your hand, there is help text that says, "Shift + Scroll to flip pages," but that key combination does not do anything. Looking in the key mappings, I do not see anything that is associated with that action, and I don't see any entries that are unmapped that look appropriate.

**Comment by thephoenixlodge** [comment]
that's to let you turn the pages of the spell recipe when you don't have the UI open. It does display 2 pages at once there though, so unless you've got a crazy complex spell recipe, it generally is displaying all the pages in the recipe as is. Turning pages with the UI open is done with the arrows at the bottom of the UI.
