### ISSUE TITLE
Crash in Dimensional Doors trap

### ISSUE THREAD

**Issue by DynamOdin** [thephoenixlodge/Heavens-of-Sorcery#70]
Setting of a specific trap in the Dimensional Doors dungeon (the one that shoots arrows and fireballs out of dispensers) causes the world to crash.
The only way to recover from this crash is to set removeErroringEntities and removeErroringTileEntities in forge.cfg to true.
[crash-2020-08-27_17.13.31-server.txt](https://github.com/thephoenixlodge/Heavens-of-Sorcery/files/5137358/crash-2020-08-27_17.13.31-server.txt)

**Comment by ewanm89** [comment]
Are you wearing any Aether items like the repulsion shield?

**Comment by DynamOdin** [comment]
I have the invisibility cloak, regeneration stone, iron bubble and power gloves, but not the repulsion shield. Usually those items should not mess with projectiles.

**Comment by ewanm89** [comment]
The stack trace says it is the Aether projectile impact event that crashed when taking damage from a tipped arrow, so it is something to do with Aether.

**Comment by ewanm89** [comment]
And just checked, it is already fixed in the next version of Aether which was released after the last pack update.

**Comment by thephoenixlodge** [comment]
Resolved by updating Aether for the 0.10 pack update
