### ISSUE TITLE
Dynamic Tree recipe converted vanilla saplings revert to their Dynamic Tree equivalent when planted

### ISSUE THREAD

**Issue by e-SonOfAnder** [thephoenixlodge/Heavens-of-Sorcery#74]
In an attempt at generating some Podzol, I took the two vanilla Spruce Saplings that I had found in Dungeon Raids, and used the Dynamic Trees recipe of combining a Spruce Cone and Dirt Bucket to create two more Spruce Saplings, but when these saplings are planted, they do not act like the vanilla saplings, but instead behave as if they are Spruce Cones, and in fact when they are broken, all of them converted to Spruce Cones, including the two that I had found in the Dungeon Raids.

**Comment by thephoenixlodge** [comment]
this is intended
