### ISSUE TITLE
Quests have pre-requisites that are not listed in the quest book

### ISSUE THREAD

**Issue by e-SonOfAnder** [thephoenixlodge/Heavens-of-Sorcery#75]
While working on the "Lighten Up" quest, it did not complete after finishing all of the listed steps for it. I looked at the Advancements page, and there the quest shows 3/4 steps completed. If you hold shift there, it shows a pre-requisite of "Completed Mana Management". This is not stated anywhere in the quest book. I had completed this one by finding a mana pearl in a dungeon in the Aether. If there are going to be dependencies like this, it should be listed in the quest book as well.

**Comment by thephoenixlodge** [comment]
Quests require their parent quests, in all cases. They mostly only show up in the book if you've already completed the parent quests. Unfortunately, Patchouli only allows specifying ONE prerequisite, while some quests have 2 or occasionally even more. In this case, it's more my bad that I added an item to loot that allowed bypassing that other quest.
