### ISSUE TITLE
Starlight Crafting Alter - Wrong Link to Bucket of Starlight

### ISSUE THREAD

**Issue by HalestormXV** [thephoenixlodge/Heavens-of-Sorcery#76]
As the title indicates the Starlight Crafting Alter shows and states a Liquid Starlight Bucket but when clicking for the recipe it takes you to Liquid Nacre Bucket recipe.

**Comment by thephoenixlodge** [comment]
Known issue I can't do anything about. The recipe link doesn't differentiate by NBT, which is all that's different between various buckets of fluid
