### ISSUE TITLE
[SUGGESTION] Slight Adjustment - Detox Items - Misty World

### ISSUE THREAD

**Issue by HalestormXV** [thephoenixlodge/Heavens-of-Sorcery#77]
So this is a Slight Issue as a matter from my perspective in sinking hours into this modpack. Misty World Toxicity, and not the wash off with Soap kind increases rather rapidly, especially when one has to dig around Bedrock to find the Astral Sorcery ores. Misty World by design makes the Detox Items (Mushrooms, Berries, etc.) in my opinion superbly rare. This isn't a problem as if you spend enough time travelling the different zones you will find the items as I believe they are Biome Temperature dependent as opposed to Biome Specific. That being said, once the Toxicity climbs as you know your Maximum health is decreased hindering further progression to a degree.

Now I see you added GameStages to the pack recently. My suggestion is perhaps allow the Ritual Summoning to be able to conjure some of the detox items but requiring some of the Botania and Misty World items since by the time you are at the point you are in the Misty World. Perhaps a Ruin of Water and Earth would be requirements in addition to whatever other items are deemed appropriate. Alternatively, perhaps creation can be locked behind a GameStage although "retro-implementing" that may be a challenge. (I have yet to work with Patchouli so I am not too familiar with its functionality)

This is just a minor suggestion. As i said, this is subjective. Some may not feel their pace is hindered and may like it as is or may be finding the Detox items easily.

**Comment by gattsuru** [comment]
Milk does reduce Toxicity, albeit very slowly (~0.2% per bucket).  Not a great solution, but can keep it from being a complete progression blocker.

Making your first cow can be a little expensive, but doable at the Nether stage.

**Comment by thephoenixlodge** [comment]
Nightberries are actually also farmable, which has been noted in the book for the coming 0.10 update. At this stage I don't believe it is necessary to add recipes to craft detox items
