### ISSUE TITLE
Can't take food from Cuisine Wok

### ISSUE THREAD

**Issue by Nix2081** [thephoenixlodge/Heavens-of-Sorcery#82]
Can't take food placed on Wok + Firepit construct from Cuisine mod. Tried left/right clicking with empty hand and with spatula - no effect. Breaking construct destroys the food.

**Comment by ewanm89** [comment]
cuisine plate?

**Comment by Nix2081** [comment]
It is called Wok on a Fire Pit

**Comment by thephoenixlodge** [comment]
Dude, he means you need to use a plate to collect the final dish.
