### ISSUE TITLE
"A Link to the Stars" quest not possible to complete (as written)

### ISSUE THREAD

**Issue by e-SonOfAnder** [thephoenixlodge/Heavens-of-Sorcery#85]
In the current version of the modpack as published and available through the Twitch launcher, it is not possible to finish the quest, "A Link to the Stars". The directions from the quest book say to use the Linking Tool to link one of the floating crystals in the Aether to Iron Ore from Misty World to convert it to Starmetal Ore. The linking process happens, and the visual effects show the crystal linked to the Iron Ore, but it never converts to Starmetal Ore. Have waited for over 10 minutes, and nothing happens.

Edit: The floating crystal apparently needs direct sky access which does not occur naturally, and is not noted as part of the quest materials. So the quest can be completed, just not as written.

**Comment by ewanm89** [comment]
I would point out sky access is noted in the astral tome, and also sky access is important for just about everything in astral sorcery, there are some exceptions, but those are relatively rare.

**Comment by e-SonOfAnder** [comment]
As I've mentioned elsewhere, you should not make assumptions about a player's familiarity with any given mod in the pack. Does it mention that in the Astral Tome? Yes, albeit I don't remember where I dug through it and found it significantly after the fact.  If there are pre-requisites for completing a task in the quest book, they should either be noted, or the player guided to where the information can be found.

In this specific instance, things look like they should be working; the chat message shows that the block gets linked, you get the particle effect showing the crystal linked to the block, and then nothing. I would never have thought to check the book for further information about something that looks like it is working.

Since the modpack makes some pretty significant changes to the default behavior of several of the mods, just directing them to the in game book of each mod isn't always helpful or sufficient, as some things will simply not exist as described there.

**Comment by thephoenixlodge** [comment]
resolved by https://github.com/thephoenixlodge/Heavens-of-Sorcery/commit/9e219385bcfd683c1a5295b0283cf7a37fe90ea2
