### ISSUE TITLE
Offerings Table - Does NOT Accept Any Flower

### ISSUE THREAD

**Issue by HalestormXV** [thephoenixlodge/Heavens-of-Sorcery#87]
Contrary to what the Quest Entry says when building the Offering Table the structure calls to be surrounded by flowers. The book says **any** flower and it would appear this is not the case as the structure will not complete. Perhaps it is intended to say any _minecraft_ flower? Or perhaps an entry needs be made in one of the tweaks to indeed let the structure accept any flower.

**Comment by ewanm89** [comment]
Not one vanilla minecraft flower here, it excepts any that extends the minecraft flower class: 
![image](https://user-images.githubusercontent.com/135458/92306416-d5368e80-ef86-11ea-9ca3-80f2a8b1bb53.png)

**Comment by HalestormXV** [comment]
Lmfao, I didn't even think to try Botania flowers. I did Inspiration's flowers, I did the "Tall flowers" like the Roses and the lilacs, I did the purple ones with the P, I did Sunflowers lmfao and the one flower type of flower I didn't try was Botania. Well alright then. Guessing this is a closed? Lol
