### ISSUE TITLE
How can i get tin?

### ISSUE THREAD

**Issue by DonMarijuano** [thephoenixlodge/Heavens-of-Sorcery#88]
sorry if this is dumb but im kinda new to Embers on its own and im not quite sure how to get tin in the heavens mod pack. can anyone help please?

**Comment by DonMarijuano** [comment]
nvm i figured it out i found some icestone

**Comment by gattsuru** [comment]
In Heaven's of Sorcery, tin nuggets can be made by placing Iron Dust, Icestone (found at lower altitudes in the Aether), and Mana Powder (made from Redstone tossed into a Botania Mana Pool), thrown into a pool of Wizardry Mana (made from putting Infused Pasture seeds into water in a Cauldron) consisting of at least six source blocks.
