### ISSUE TITLE
Quests Not Completing

### ISSUE THREAD

**Issue by hopey3182** [thephoenixlodge/Heavens-of-Sorcery#9]
Basically I've had a few quests already (Millhouse and Stoneage) that I've had trouble completing. I had to craft 3 mills before the millhouse quest worked and I am still unable to complete the stoneage one after mining 3 pieces and obsidian and way more than 10 cobble.

**Comment by Saphrym** [comment]
I had the same thing happen during stream today. It always started after I did a shift to live and got that weird block placing mod activated. If I logged out of the world and back in, the quests could complete until I activated that mod again. I turned it off using the key for it, reloaded the world, and didn't have the problem again.

**Comment by thephoenixlodge** [comment]
Resolved in 0.9.3.1 by removing Linear
