### ISSUE TITLE
Broken 0.10 Server Pack from Curseforge/Twitch

### ISSUE THREAD

**Issue by antiism** [thephoenixlodge/Heavens-of-Sorcery#90]
Zipfile contains a duplicate older LittleTiles "LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar" causing a startup crash. deleting file fixes crash. Also it seems as if "patchouli_books" was updated for the client but not the server. i dont know if this is intentional.

**Comment by ewanm89** [comment]
Oops missed one. Uploading new version now. As for patchouli_books, wasn't deliberate, but I think that is mostly client anyway.
