### ISSUE TITLE
Two slime "recipes".

### ISSUE THREAD

**Issue by LordPinkerton** [thephoenixlodge/Heavens-of-Sorcery#95]
The Ritual Table has two entries for Conjure Slime. One that requires a slime ball and one that requires bacterial shale. Don't know if Slimes are supposed to be gated until you can acquire slime balls.

**Comment by thephoenixlodge** [comment]
That's exactly as intended. The Bacterial shale one is added to get you initial slime, while the default one using a slime ball can be done using the slimeballs you get from killing summoned ones without needing to go mine for bacterial shale more
